### ISSUE TITLE
Monorepo migration - bring "Data Magic" into the primary repo

### ISSUE THREAD

**Issue by futuresoup** [climate-tech-handbook/climate-tech-handbook#123]
It's time to get the dirty [Data Magic](https://github.com/climate-tech-handbook/data-magic/) repo cleaned up and merged into our primary repo.

Tasks:
- [ ] Copy over the Flask back-end (App folder)
- [ ] Migrate Issue tickets over
- [ ] Get the Flask app deployed and API accessible
- [ ] Create a production branch and deployment workflow
- [ ] Rename "Data Magic" repo to "Playground" if we want to continue running experiments though, or just nuke it!
- [ ] Update documentation

**Comment by ArLough** [comment]
Thinking ahead to deployment, here is one article I was reading about a possible way to do it
https://testdriven.io/blog/flask-render-deployment/

**Comment by futuresoup** [comment]
@shreeup has been playing around with deploying "Data Magic" to Vercel.

If it's a better fit than another host, that's awesome.

My main concern is price - would I have to pay for both Netlify & Vercel? That starts to add up on top of the other project costs.

I suppose whatever we use to host this thing will have a cost to it beyond Netlify? Or can we consolidate?

**Comment by shreeup** [comment]
i am going to delete venv folder from data-magic github repo (https://github.com/climate-tech-handbook/data-magic/tree/main/venv) . i think it is not really used and make the project heavy, in an effort to make it easier to deploy

**Comment by ArLough** [comment]
> My main concern is price - would I have to pay for both Netlify & Vercel? That starts to add up on top of the other project costs.
> 
> I suppose whatever we use to host this thing will have a cost to it beyond Netlify? Or can we consolidate?

Netlify does have serverless functions as an offering, but I'll have to look into it and see if it fits our use case.

**Comment by ArLough** [comment]
> I don't imagine switching to Docusaurus (Node / React) changes anything when it comes to Flask, but if it does let me know, as I am not a developer.
> 
> I also don't know if Flask has limitations as the project scales. If so, please share those opinions.

I don't think the Docusaurus switch will affect anything. Flask itself has a reputation as best for side projects and smaller web apps. But, I think it should work at least in the immediate future. There are alternatives that are still Python based like Django and FastAPI that are meant for more production sites and larger websites. But, I think we should be able to make that switch in the future if needed. FastAPI in particular looks very similar to Flask/

**Comment by shreeup** [comment]
I was able to deploy docker image to render platform, 
https://climatetechdatamagic.onrender.com/hello
but post endpoints are not really working.. will have to figure this out
Error

 Traceback (most recent call last):
Jun 14 09:47:31 PM    File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
Jun 14 09:47:31 PM      response = self.full_dispatch_request()
Jun 14 09:47:31 PM    File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
Jun 14 09:47:31 PM      rv = self.handle_user_exception(e)
Jun 14 09:47:31 PM    File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
Jun 14 09:47:31 PM      rv = self.dispatch_request()
Jun 14 09:47:31 PM    File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
Jun 14 09:47:31 PM      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
Jun 14 09:47:31 PM    File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1890, in ensure_sync
Jun 14 09:47:31 PM      return self.async_to_sync(func)
Jun 14 09:47:31 PM    File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1911, in async_to_sync
Jun 14 09:47:31 PM      raise RuntimeError(
Jun 14 09:47:31 PM  RuntimeError: Install Flask with the 'async' extra in order to use async views.

Steps:

Build docker image push to docker hub

```
docker image build -t datamagic_docker .
docker run --platform linux/amd64 -p 5000:5000 -d datamagic_docker
docker login
docker tag datamagic_docker shreeupadhyaya/datamagic_docker
docker push shreeupadhyaya/datamagic_docker
```

deploy image from docker hub to render
    https://render.com/docs/deploy-an-image

**Comment by ArLough** [comment]
I experienced the same async issue on my local machine. It was resolved by doing 'pip install asgiref' for me

https://stackoverflow.com/questions/70321014/runtimeerror-install-flask-with-the-async-extra-in-order-to-use-async-views

**Comment by shreeup** [comment]
Ok now I am able to invoke post methods in hosted platform.

This is image from docker logs which show that post endpoints invocation was successful and returned 200.
![image](https://github.com/climate-tech-handbook/climate-tech-handbook/assets/16798480/5ba10076-af1c-45de-b7e1-b6513117a587)


I am also attaching screenshot of postman returning 200 for one of endpoint

![image](https://github.com/climate-tech-handbook/climate-tech-handbook/assets/16798480/6e6fcf38-e7f9-4e71-872f-4957a5010413)
